# Generated by Django 5.1.4 on 2024-12-23 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coluna1', models.CharField(max_length=100, verbose_name='Coluna1')),
            ],
        ),
    ]
