# Generated by Django 5.1.4 on 2024-12-27 19:38

import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data da última atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('icone_imagem', stdimage.models.StdImageField(force_min_size=False, upload_to='', variations={}, verbose_name='Imagem do ícone')),
                ('icone', models.CharField(choices=[('ln-cog', 'Engrenagem'), ('lni-statis-up', 'Gráfico'), ('lni-user', 'Usuários'), ('lni-layers', 'Design'), ('lni-mobile', 'Mobile'), ('lni-rocket', 'Foguete')], max_length=13, verbose_name='ícone')),
                ('servico', models.CharField(max_length=100, verbose_name='Nome do Serviço')),
                ('descricao', models.TimeField(max_length=500, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
            },
        ),
        migrations.DeleteModel(
            name='Teste',
        ),
    ]
