# Generated by Django 5.1.4 on 2024-12-27 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cargo_remove_servico_icone_imagem_funcionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='descricao',
            field=models.TextField(max_length=500, verbose_name='Descrição'),
        ),
    ]
