# Generated by Django 5.1.4 on 2024-12-28 16:27

import core.models
import django.core.validators
import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_feature_icone_alter_servico_icone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depoimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data da última atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('foto', stdimage.models.StdImageField(force_min_size=False, upload_to=core.models.get_file_path, variations={'thumb': {'crop': True, 'height': 75, 'width': 75}}, verbose_name='Foto do cliente')),
                ('nome', models.CharField(max_length=70, verbose_name='Nome')),
                ('profissao', models.CharField(max_length=70, verbose_name='Profissão')),
                ('estrelas', models.DecimalField(decimal_places=0, max_digits=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Número de estrelas')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data da última atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('icone', models.CharField(choices=[('lni-cog', 'Engrenagem'), ('lni-stats-up', 'Gráfico'), ('lni-users', 'Usuários'), ('lni-layers', 'Design'), ('lni-mobile', 'Mobile'), ('lni-rocket', 'Foguete'), ('lni-leaf', 'Folha'), ('lni-laptop-phone', 'Dispositivos'), ('lni-package', 'Pacote'), ('lni-drop', 'Gota'), ('lni-star', 'Estrela'), ('lni-star-filled', 'Estrela Cheia'), ('lni-star-half', 'Estrela Vazia')], max_length=16, verbose_name='ícone')),
                ('nome', models.CharField(max_length=20, verbose_name='Nome')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('numero_usuarios', models.DecimalField(decimal_places=0, max_digits=6, verbose_name='Número máximo de usuários')),
                ('armazenamento', models.DecimalField(decimal_places=0, max_digits=4, verbose_name='Limite máximo de armazenamento')),
                ('suporte', models.CharField(verbose_name='Tipo de suporte')),
                ('atualizacoes', models.CharField(default='Lifetime updates', max_length=50, verbose_name='Atualizações')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='feature',
            name='icone',
            field=models.CharField(choices=[('lni-cog', 'Engrenagem'), ('lni-stats-up', 'Gráfico'), ('lni-users', 'Usuários'), ('lni-layers', 'Design'), ('lni-mobile', 'Mobile'), ('lni-rocket', 'Foguete'), ('lni-leaf', 'Folha'), ('lni-laptop-phone', 'Dispositivos'), ('lni-package', 'Pacote'), ('lni-drop', 'Gota'), ('lni-star', 'Estrela'), ('lni-star-filled', 'Estrela Cheia'), ('lni-star-half', 'Estrela Vazia')], max_length=16, verbose_name='ícone'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('lni-cog', 'Engrenagem'), ('lni-stats-up', 'Gráfico'), ('lni-users', 'Usuários'), ('lni-layers', 'Design'), ('lni-mobile', 'Mobile'), ('lni-rocket', 'Foguete'), ('lni-leaf', 'Folha'), ('lni-laptop-phone', 'Dispositivos'), ('lni-package', 'Pacote'), ('lni-drop', 'Gota'), ('lni-star', 'Estrela'), ('lni-star-filled', 'Estrela Cheia'), ('lni-star-half', 'Estrela Vazia')], max_length=16, verbose_name='ícone'),
        ),
    ]
